### PR TITLE
Added Bright Data details

### PR DESCRIPTION
**Pull request by palbee**
Injecting the Bright Data details.

### CODE REVIEW

**Review by arun-gupta — CHANGES_REQUESTED** [review]
This is far too much detail for this page. Can you provide a high level summary and link to existing web pages? Please do not exceed 2-3 paragraphs.

**Comment by danielpi-bright-data** [comment]
> This is far too much detail for this page. Can you provide a high level summary and link to existing web pages? Please do not exceed 2-3 paragraphs.

@arun-gupta  
Fixed

**Comment by arun-gupta** [comment]
@danielpi-bright-data I still see ~60 lines of text. Can you bring it down to ~10-15? We need to make sure all credits are equitable.

**Comment by danielpi-bright-data** [comment]
> @danielpi-bright-data I still see ~60 lines of text. Can you bring it down to ~10-15? We need to make sure all credits are equitable.

@arun-gupta the changes were made here: https://github.com/danielpi-bright-data/information-2024/blob/patch-1/Credits-and-Collaborators.md
Perhaps I fixed on the patch-1 by mistake?
2024-09-23_15h48_40

**Comment by danielpi-bright-data** [comment]
@arun-gupta Checking to see that our updates are approved and there are no additional adjustments needed.

**Comment by arun-gupta** [comment]
@danielpi-bright-data I'm still seeing 60 LOCs. You can close this PR and open up a new PR, if you prefer
image

**Review by arun-gupta — CHANGES_REQUESTED** [review]
Still seeing the older changes

**Comment by danielpi-bright-data** [comment]
@arun-gupta 
https://github.com/danielpi-bright-data/information-2024/blob/main/Credits-and-Collaborators.md
Added to the main branch, please review

**Review by arun-gupta — CHANGES_REQUESTED** [review]
I am still seeing the same ~60 lines. Please trim down the content to 2 paragraphs. I recommend closing this PR and opening a new clean PR with reduced text.

**Pull request closed without merging**
